Unstuctured storage variable hash strings
lidofinance/lido-dao pull request #232
Opened 2020-12-07 16:02 UTC by lxzrv

Closes #206

2020-12-07 16:18 UTC, ongrid requested changes
Pausable.sol still contains old notation
NodeOperatorsRegistry.sol not touched at all

2020-12-07 16:18 UTC, ongrid commented on contracts/0.4.24/Lido.sol
> +    bytes32 internal constant VALIDATOR_REGISTRATION_VALUE_POSITION = keccak256("validatorRegistration.lido.lido.eth");
rename `validatorRegistration` to `depositContract`, Everywhere. It's the old deprecated name.

2020-12-07 16:18 UTC, ongrid commented on contracts/0.4.24/Lido.sol
> +    bytes32 internal constant NODE_OPERATORS_FEE_VALUE_POSITION = keccak256("operatorsFee.lido.lido.eth");
nodeOperatorsFee

2020-12-07 16:18 UTC, ongrid commented on contracts/0.4.24/Lido.sol
> +    bytes32 internal constant VALIDATOR_REGISTRATION_VALUE_POSITION = keccak256("validatorRegistration.lido.lido.eth");
Do this with separate commit

2020-12-08 06:37 UTC, ongrid requested changes
1. need to rebase to the HEAD of origin/pre-mainnet-refactoring (coordinated with @skozin to use pre-mainnet-refactoring as the develop branch)
2. All mentioning of deposit_contract.vy should be renamed to deposit_contract.sol (has been migrated from Vyper to Solidity). Irrelevant comments should be removed, I've highlighted them
3. A lot of cosmetics, read the resulting text before

2020-12-08 06:37 UTC, ongrid commented on apps/lido/app/src/App.js
> +      depositContractContract,
just depositContract

2020-12-08 06:37 UTC, ongrid commented on apps/lido/app/src/App.js
> +        label: 'Deposit contract Contract',
just depositContract

2020-12-08 06:37 UTC, ongrid commented on apps/lido/app/src/App.js
> +        content: <IdentityBadge entity={depositContractContract} />,
just depositContract

2020-12-08 06:37 UTC, ongrid commented on contracts/0.4.24/Lido.sol
> +    uint256 internal constant MIN_DEPOSIT_AMOUNT = 1 ether;     // deposit_contract.vy
the comment // deposit_contract.vy is irrelevant here. Remove it

2020-12-08 06:37 UTC, ongrid commented on contracts/0.4.24/Lido.sol
> +    uint256 internal constant DEPOSIT_AMOUNT_UNIT = 1000000000 wei;     // deposit_contract.vy
the comment // deposit_contract.vy is irrelevant here. Remove it

2020-12-08 06:37 UTC, ongrid commented on docs/protocol-levers.md
> +deactivated operators during deposit contract; also, deactivated operators don’t
This shouldn't be changed. See the context, it's not about deposit contract.

2020-12-08 06:37 UTC, ongrid commented on test/scenario/lido_happy_path.js
> +    // The first 32 ETH chunk was deposited to the deposit contract contract,
just "deposit contract"

2020-12-09 09:20 UTC, ongrid approved these changes

2020-12-15 00:03 UTC, skozin approved these changes

2020-12-15 00:03 UTC, merged