Increase test coverage
lidofinance/lido-dao pull request #235
Opened 2020-12-10 13:45 UTC by lxzrv

Closes #224

2020-12-10 14:57 UTC, ongrid requested changes

2020-12-10 14:57 UTC, ongrid commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +            require(ERC20(_token).safeTransfer(operator.rewardAddress, reward), "TRANSFER_FAILED");
move the proposal to remove `_token` from `distributeRewards()` args to the separate issue. This is not related to coverage.

2020-12-10 14:57 UTC, ongrid commented on contracts/0.4.24/test_helpers/TestLido.sol
> +
Let's rename all contracts with `Test...` names to `Mock...` since they're mocks, not tests

2020-12-10 14:57 UTC, ongrid commented on contracts/0.4.24/test_helpers/TestLido.sol
> +    function setValidatorRegistrationContract(IValidatorRegistration _contract) public {
Note: rename to `...DepositContract` after another PR with renaming will be merged

2020-12-15 08:35 UTC, lxzrv commented
Result:
```
-----------------------------|----------|----------|----------|----------|----------------|
File                         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------------------|----------|----------|----------|----------|----------------|
 0.4.24/                     |      100 |    86.17 |      100 |      100 |                |
  Lido.sol                   |      100 |    82.86 |      100 |      100 |                |
  StETH.sol                  |      100 |    95.83 |      100 |      100 |                |
 0.4.24/interfaces/          |      100 |      100 |      100 |      100 |                |
  IDepositContract.sol       |      100 |      100 |      100 |      100 |                |
  ILido.sol                  |      100 |      100 |      100 |      100 |                |
  ILidoOracle.sol            |      100 |      100 |      100 |      100 |                |
  INodeOperatorsRegistry.sol |      100 |      100 |      100 |      100 |                |
  ISTETH.sol                 |      100 |      100 |      100 |      100 |                |
 0.4.24/lib/                 |      100 |    83.33 |      100 |      100 |                |
  MemUtils.sol               |      100 |       50 |      100 |      100 |                |
  Pausable.sol               |      100 |      100 |      100 |      100 |                |
 0.4.24/nos/                 |      100 |    84.44 |      100 |      100 |                |
  NodeOperatorsRegistry.sol  |      100 |    84.44 |      100 |      100 |                |
 0.4.24/oracle/              |    98.72 |    84.62 |    96.15 |    98.77 |                |
  Algorithm.sol              |      100 |       90 |      100 |      100 |                |
  BitOps.sol                 |      100 |       70 |      100 |      100 |                |
  LidoOracle.sol             |    98.32 |    86.21 |    95.45 |    98.33 |        431,462 |
-----------------------------|----------|----------|----------|----------|----------------|
All files                    |    99.66 |    85.07 |    99.29 |    99.67 |                |
-----------------------------|----------|----------|----------|----------|----------------|
```

2020-12-15 09:50 UTC, ongrid approved these changes

2020-12-15 09:50 UTC, ongrid commented on test/0.4.24/lidooracle.test.js
> +    const receipt = await app.getBeaconSpec()
it's not the receipt IMO

2020-12-15 09:50 UTC, ongrid commented on contracts/0.4.24/oracle/LidoOracle.sol
> +        require(_epochsPerFrame > 0, "BAD_ARGUMENT");
reasons should be specific "BAD_EPOCHS_PER_FRAME"

2020-12-15 22:57 UTC, merged