Pre mainnet oracle fixes
lidofinance/lido-dao pull request #257
Opened 2020-12-15 11:59 UTC by lxzrv

Closes #248

2020-12-16 09:58 UTC, ongrid requested changes
@lxzrv need rebase on develop's HEAD and resolve conflicts.

2020-12-18 08:46 UTC, ongrid approved these changes

2021-01-27 10:05 UTC, Eenae approved these changes

2021-01-29 18:45 UTC, dechjo commented on contracts/0.4.24/oracle/LidoOracle.sol
> +        MIN_REPORTABLE_EPOCH_ID_POSITION.setStorageUint256(maxReportedEpochId);
mistype?.. investigating...

2021-01-30 15:23 UTC, vshvsh commented on contracts/0.4.24/oracle/LidoOracle.sol
> +            if (maxReportedEpochId != minReportableEpochId) {
You're right it's not a good idea. Up to 7200 iterations in a good day, unlimited in a bad network weather. 

Ditching old data on quorum change is acceptable, though. Needs to be documented but acceptable.

2021-02-06 12:03 UTC, dechjo commented on contracts/0.4.24/oracle/LidoOracle.sol
> +            if (maxReportedEpochId != minReportableEpochId) {
@vshvsh, where do you think to document it? https://github.com/lidofinance/lido-dao/blob/develop/docs/protocol-levers.md#lidooraclesol?

2021-02-06 12:04 UTC, dechjo commented
Manually merged to `oracle-v2` branch, see #292.

2021-02-06 12:04 UTC, closed without merging