New quorum calculation
lidofinance/lido-dao pull request #277
Opened 2020-12-24 11:43 UTC by lxzrv

Introduces alternative quorum calculation mechanics to oracle contract

2020-12-24 13:39 UTC, ongrid requested changes
* Describe the problem it solves in the commit message(s) or create the issue for the bug. Now it's unclear.
* Avoid `for` loop in test. Just random garbage "1234", "2345" and so on. To be trivial and readable.
* Add user story what is going on like "Within `members > 4` and `quorum > 2` configuration oracles gone crazy by any reason and started reporting garbage data. But two oracles reported the same value so two conditions get fulfilled as a result - array become unimodal and quorum got reached. So the garbage report gets pushed to the Lido."
* Add trivial failing test that gets fixed with the updated implementation.

2020-12-25 14:10 UTC, ongrid requested changes

2020-12-25 14:10 UTC, ongrid commented on contracts/0.4.24/oracle/LidoOracle.sol
> +    function _findQuorumValue(uint256 quorum, uint256[] data) internal pure returns (bool isQuorum, uint256 quorumValue) {
_findQuorumValue is non-trivial and need to be unit-tested. Expose it using mock and cover separately against different inputs.

2020-12-28 14:25 UTC, ongrid requested changes

2020-12-28 14:25 UTC, ongrid commented on test/0.4.24/lidooracle.test.js
> +      await assertReportableEpochs(0, 0)
I'd suggest to use more direct approach for better readability - assert 'Completed' not in events.
+ keep assertReportableEpochs

2020-12-28 14:25 UTC, ongrid commented on test/0.4.24/lidooracle.test.js
> +      // mode when certain number of reports recieved.
Too overcomplicated. The explanation should be simpler:

Previous implementation:
if N members submitted some random garbage and the array is unimodal (contains duplicate reports), it gets pushed (once N >= quorum).

New implementation:
Report get pushed to lido only if N+ members submitted strictly same numbers.

Test checks that previous behaviour got fixed (unimodal data doesn'r get submitted until the quantity of equal reports equals quorum)

2020-12-29 12:19 UTC, ongrid requested changes
Looks good. But solidity coverage got silently broken on CI

<img width="1103" alt="Screenshot 2020-12-29 at 15 18 09" src="https://user-images.githubusercontent.com/7992612/103283264-1eed2e00-49e9-11eb-90fe-558013bf515c.png">

2020-12-29 12:26 UTC, ongrid commented
It's broken for 2 weeks already. Raised issue #279

2020-12-29 12:27 UTC, ongrid approved these changes

2021-01-26 08:29 UTC, dechjo commented
This merge request is superseded with https://github.com/lidofinance/lido-dao/pull/282.

2021-02-01 06:25 UTC, vshvsh commented
Replaced by #282

2021-02-01 06:25 UTC, closed without merging