Remove blockHash arg from pauseDeposits() method
lidofinance/lido-dao pull request #362
Opened 2021-10-13 18:59 UTC by Psirex

2021-10-13 20:13 UTC, ujenjt requested changes
Style fix, the rest looks good

2021-10-13 20:13 UTC, ujenjt commented on contracts/0.8.9/DepositSecurityModule.sol
> +            bytes32 msgHash = keccak256(abi.encodePacked(PAUSE_MESSAGE_PREFIX,blockNumber));
PAUSE_MESSAGE_PREFIX,blockNumber -> PAUSE_MESSAGE_PREFIX, blockNumber

2021-10-13 20:13 UTC, ujenjt commented on contracts/0.8.9/DepositSecurityModule.sol
> +            bytes32 msgHash = keccak256(abi.encodePacked(PAUSE_MESSAGE_PREFIX,blockNumber));
space plz

2021-10-14 08:33 UTC, Psirex commented on contracts/0.8.9/DepositSecurityModule.sol
> +            bytes32 msgHash = keccak256(abi.encodePacked(PAUSE_MESSAGE_PREFIX,blockNumber));
Done

2021-10-14 09:07 UTC, merged