Aragon Frontops
lidofinance/lido-dao pull request #368
Opened 2021-12-06 10:00 UTC by loga4

+ add lido-cli tool for run local aragon

* fix deploy script to local node
* fix lido apps
* fix problem with yarn v2

2022-01-16 09:35 UTC, arwer13 commented on docs/dev-fork.md
> +You need an Infura with [Archived Data](https://infura.io/docs/ethereum/add-ons/archiveData) access
Either `an Infura node` or `Infura` would be more correct
The same is for Alchemy

2022-01-16 09:35 UTC, arwer13 commented on docs/dev-fork.md
> +That script set the right environment variables, download and start Aragon client at `http://localhost:3000/#/lido-dao.aragonid.eth`
"sets", "downloads", etc

2022-01-16 09:35 UTC, arwer13 commented on docs/dev-fork.md
> +Actual information about AppID you can find in `deployed-mainnet.json`, for example, id of Lido app:
I guess it would be more correct "the actual information ... can be found in ..." or "You can find the actual information ..."

2022-01-16 09:35 UTC, arwer13 commented on docs/dev-local.md
> +below assume `localhost` target network.
--> "below assume `localhost` is the target network.

2022-01-16 09:35 UTC, arwer13 commented on docs/dev-local.md
> +You may specify any number additional keys inside any network state, they will be left intact by
--> "You may specify any number _of_ additional keys"

2022-01-16 09:35 UTC, arwer13 commented on docs/dev-local.md
> +IPFS needed to upload an Aragon Apps like (Finance, Voting, etc...) and Lido apps (Lido, LidoOracle,NOS)
--> "IPFS _is_ needed

2022-01-16 09:35 UTC, arwer13 commented on scripts/deploy-lido-apps.js
> +      // '--skip-app-build',
Is this intended to be commented out?

2022-01-16 09:35 UTC, arwer13 commented on scripts/deploy-lido-apps.js
> +  // console.log({res})
Obsolete, I guess

2022-01-16 23:42 UTC, TheDZhon requested changes
Could you please provide a feedback on the `aragon-cli` issue.

2022-01-16 23:42 UTC, TheDZhon commented on cli/build/SHA256SUM
> +28790f18d4e96c4c72a8639bb2dd9edc3ac47eaf10e3d323a64d3e9a1ad36c5f  lido-aragon_darwin_amd64
The stored in the repo `aragon-cli` was built for the MAC OS platform.
I got `~/workspace/lido-dao/cli/ ./lido-aragon 
zsh: exec format error: ./lido-aragon` without any clues on error reasons.

Seems like a blocker to merge cause even running the `make` command doesn't solve the problem (I need manually overwrite the file). 

[The `aragon-cli` documentation](https://github.com/lidofinance/lido-dao/blob/aragon-dev/docs/lido-aragon.md) have nothing about this case.

2022-01-17 07:14 UTC, TheDZhon commented on cli/pkg/contracts/compile.go
> +	s, _ := pterm.DefaultSpinner.Start("Contracs: compile...")
Just a small typo which is visible in logs: `contracs` → `contracts`

2022-01-17 07:47 UTC, TheDZhon commented on cli/cmd/start.go
> +		Lido.HardhatNode.Start("")
I got the following error when trying to restart already terminated lido-aragon:

>  `lido-aragon start all -v`
...
All done!
 SUCCESS  Contracs: compile...done                                                                                                                                                                                                     
  ERROR   Hardhat node: Starting...                                                                                                                                                                                                    
  ERROR   Error: listen EADDRINUSE: address already in use 127.0.0.1:8545
              at Server.setupListenHandle [as _listen2] (net.js:1316:16)
              at listenInCluster (net.js:1364:12)
              at doListen (net.js:1501:7)
              at processTicksAndRejections (internal/process/task_queues.js:85:21)
▀  IPFS: Starting... (1s)Initializing daemon...

2022-01-17 08:51 UTC, TheDZhon commented on cli/cmd/start.go
> +		Lido.HardhatNode.Start("")
It's reproducible after abnormal termination (via ctrl+c in the middle of something or another thrown error). It's just a `hardhat node` that sits on the port and could be easily killed by the SIGTERM signal.
Also, sometimes we need to delete the `deployed-localhost.json` to recover completely.

2022-01-24 15:43 UTC, TheDZhon approved these changes

2022-01-29 11:40 UTC, merged